<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'wPjWvsjLyfo=');
$cfg_Cs[2]=array(0,1,1,'ILCux+nOxNXC');
$cfg_Cs[3]=array(0,1,1,'0KPUsMn6u+4=');
$cfg_Cs[4]=array(0,1,1,'tLTStcD6s8w=');
$cfg_Cs[5]=array(0,1,1,'x9fH6c7E1cI=');
$cfg_Cs[6]=array(0,1,1,'09HH6c7E1cI=');
$cfg_Cs[7]=array(0,1,1,'yfq77svmsco=');
$cfg_Cs[8]=array(0,1,1,'06LT787E1cI=');
$cfg_Cs[9]=array(0,1,1,'vq215M7E1cI=');
$cfg_Cs[10]=array(0,1,1,'yMvJ+tXcwO0=');
$cfg_Cs[11]=array(0,1,1,'yfq77rOjyrY=');
$cfg_Cs[12]=array(0,1,1,'0MTH6cjVvMc=');
$cfg_Cs[13]=array(0,1,1,'uOPQps7E1cI=');
$cfg_Cs[14]=array(7,1,1,'0MLOxbGotcA=');
?>